### ISSUE TITLE
fworld fails to run on linux

### ISSUE THREAD

**Issue by etuleu** [Astera-org/obelisk#197]
> 2022/08/03 15:47:17 vulkan warning: missing 1 required device extensions during Config
panic: vulkan error: vulkan error: extension not present (-7) on /home/erdal/go/pkg/mod/github.com/goki/vgpu@v1.0.4/vgpu/errors.go:23 (0xb34c5e)
	NewError: pc, _, _, ok := runtime.Caller(0)

goroutine 1 [running, locked to thread]:
github.com/goki/vgpu/vgpu.IfPanic(...)
	/home/erdal/go/pkg/mod/github.com/goki/vgpu@v1.0.4/vgpu/errors.go:40
github.com/goki/vgpu/vgpu.(*Device).MakeDevice(0xc0007aebb8, 0xc000157800)
	/home/erdal/go/pkg/mod/github.com/goki/vgpu@v1.0.4/vgpu/device.go:93 +0x285
github.com/goki/vgpu/vgpu.(*Surface).Init(0xc0007aebb0, 0xc000157800, 0x13e6200?)
	/home/erdal/go/pkg/mod/github.com/goki/vgpu@v1.0.4/vgpu/surface.go:89 +0x15c
github.com/goki/vgpu/vgpu.NewSurface(0x42903f0?, 0x13e6200?)
	/home/erdal/go/pkg/mod/github.com/goki/vgpu@v1.0.4/vgpu/surface.go:39 +0x48
github.com/goki/gi/oswin/driver/vkos.(*appImpl).NewWindow.func2()
	/home/erdal/go/pkg/mod/github.com/goki/gi@v1.3.5/oswin/driver/vkos/app.go:252 +0xa5
github.com/goki/gi/oswin/driver/vkos.(*appImpl).mainLoop(0x24ebbc0)
	/home/erdal/go/pkg/mod/github.com/goki/gi@v1.3.5/oswin/driver/vkos/app.go:157 +0xf6
github.com/goki/gi/oswin/driver/vkos.Main(0x1469020?)
	/home/erdal/go/pkg/mod/github.com/goki/gi@v1.3.5/oswin/driver/vkos/app.go:79 +0x91
github.com/goki/gi/oswin/driver.driverMain(...)
	/home/erdal/go/pkg/mod/github.com/goki/gi@v1.3.5/oswin/driver/driver_vkos.go:18
github.com/goki/gi/oswin/driver.Main(...)
	/home/erdal/go/pkg/mod/github.com/goki/gi@v1.3.5/oswin/driver/driver.go:27
github.com/goki/gi/gimain.Main(0xc000033a50?)
	/home/erdal/go/pkg/mod/github.com/goki/gi@v1.3.5/gimain/gimain.go:31 +0x57
main.main()
	/home/erdal/dev/obelisk/obelisk/infra/odpw/temp/d67776b/obelisk/worlds/integrated/fworld/fworld.go:1739 +0x12a

**Comment by etuleu** [comment]
Not sure what solved it but I upgraded everything I could related to Vulkan and nvidia drivers and then rebooted my machine and now it's working fine.
